export default [
  {
    name: 'Ana',
    color: 'red',
    url: 'https://photos.app.goo.gl/bCXy3oBYxXbLN4kK6',
    active: false,
  },
  {
    name: 'Ashe',
    color: 'red',
    url: 'https://photos.app.goo.gl/y1wbJkZMmRNuSBU7A',
    active: false,
  },
  {
    name: 'Bastion',
    color: 'red',
    url: 'https://photos.app.goo.gl/qbG3cXbfimvC4eLL8',
    active: false,
  },
  {
    name: 'Brigitte',
    color: 'red',
    url: 'https://photos.app.goo.gl/hNC8DHtxSyZRSWtN7',
    active: false,
  },
  {
    name: 'D.Va',
    color: 'red',
    url: 'https://photos.app.goo.gl/hGpdjjiCa8BDDEPh9',
    active: false,
  },
  {
    name: 'Doomfist',
    color: 'red',
    url: 'https://photos.app.goo.gl/767eMV9d9511NCe2A',
    active: false,
  },
  {
    name: 'Genji',
    color: 'red',
    url: 'https://photos.app.goo.gl/qemvJ63rFvjWePQu6',
    active: false,
  },
  {
    name: 'Hanzo',
    color: 'red',
    url: 'https://photos.app.goo.gl/c9nwa4jLRD1xmVXx9',
    active: false,
  },
  {
    name: 'Junkrat',
    color: 'red',
    url: 'https://photos.app.goo.gl/7VGGTZNt5mkfCJ7h9',
    active: false,
  },
  {
    name: 'Lúcio',
    color: 'red',
    url: 'https://photos.app.goo.gl/L8fRkrQfoNyy8uLs9',
    active: false,
  },
  {
    name: 'McCree',
    color: 'red',
    url: 'https://photos.app.goo.gl/4S9rmq7ogZSvfM188',
    active: false,
  },
  {
    name: 'Mei',
    color: 'red',
    url: 'https://photos.app.goo.gl/5CynD7jnyaNHpx7B7',
    active: false,
  },
  {
    name: 'Mercy',
    color: 'red',
    url: 'https://photos.app.goo.gl/PUUkYXjb2f15UbaC7',
    active: false,
  },
  {
    name: 'Moira',
    color: 'red',
    url: 'https://photos.app.goo.gl/eGbvWwZgeDYKd9838',
    active: false,
  },
  {
    name: 'Orisa',
    color: 'red',
    url: 'https://photos.app.goo.gl/7nVpRW7fjVQDPyYa7',
    active: false,
  },
  {
    name: 'Pharah',
    color: 'red',
    url: 'https://photos.app.goo.gl/gocaPaLERV9yCv8p8',
    active: false,
  },
  {
    name: 'Reaper',
    color: 'red',
    url: 'https://photos.app.goo.gl/8sfoLAD8V6Kg1PuT6',
    active: false,
  },
  {
    name: 'Reinhardt',
    color: 'red',
    url: 'https://photos.app.goo.gl/NYb1Zk4xpkEcogDF8',
    active: false,
  },
  {
    name: 'Roadhog',
    color: 'red',
    url: 'https://photos.app.goo.gl/Jj4Rv8xTXfFSS51UA',
    active: false,
  },
  {
    name: 'Soldier: 76',
    color: 'red',
    url: 'https://photos.app.goo.gl/HKEPS63ZoBbkdRQq8',
    active: false,
  },
  {
    name: 'Sombra',
    color: 'red',
    url: '#!',
    active: false,
  },
  {
    name: 'Symmetra',
    color: 'red',
    url: 'https://photos.app.goo.gl/g7D8SycBT5HXv1YG7',
    active: false,
  },
  {
    name: 'Torbjörn',
    color: 'red',
    url: 'https://photos.app.goo.gl/m1r17mB3yK37GD8X9',
    active: false,
  },
  {
    name: 'Tracer',
    color: 'red',
    url: 'https://photos.app.goo.gl/uMfrKeaE3mo9i2Q69',
    active: false,
  },
  {
    name: 'Widowmaker',
    color: 'red',
    url: 'https://photos.app.goo.gl/rzVJ5sSesYHWioQr5',
    active: false,
  },
  {
    name: 'Winston',
    color: 'red',
    url: 'https://photos.app.goo.gl/NnFNPyM8XtY8GsuB7',
    active: false,
  },
  {
    name: 'Wrecking Ball',
    color: 'red',
    url: '#!',
    active: false,
  },
  {
    name: 'Zarya',
    color: 'red',
    url: 'https://photos.app.goo.gl/wCgxNmRWyfYdfctXA',
    active: false,
  },
  {
    name: 'Zenyatta',
    color: 'red',
    url: 'https://photos.app.goo.gl/rND4KRenJwayifWg7',
    active: false,
  },
];
